name: Bug report
description: Отчёт о дефекте
title: "[Ошибка]: "
labels: ["bug"]
body:
  - type: textarea
    id: Description
    attributes:
      label: Описание
    validations:
      required: true
      
  - type: textarea
    id: Playback_steps
    attributes:
      label: Шаги воспроизведения
    validations:
      required: true

  - type: textarea
    id: Expected_result
    attributes:
      label: Ожидаемый результат
    validations:
      required: true

  - type: textarea
    id: Actual_result
    attributes:
      label: Фактический результат
    validations:
      required: true

  - type: textarea
    id: Additional_materials
    attributes:
      label: Скриншоты / Доп. материалы
      
  - type: textarea
    id: Execution_environment
    attributes:
      label: Среда выполнения
      placeholder: Операционная система, IDE и прочие программные особенности необходимые для нахождения дефекта

  - type: dropdown
    id: Priority
    attributes:
      label: Приоритет
      options:
       - Высокий
       - Средний
       - Низкий
    validations:
      required: true

  - type: dropdown
    id: Severity
    attributes:
      label: Серьёзность
      options:
       - Критическая
       - Высокая
       - Средняя
       - Низкая
    validations:
      required: true
